apiVersion: v1
name: finops-object-storage-exporter
version: 1.0.0
appVersion: 1.0.0
description: Finops Object Storage Chart Helm 
keywords:
- prometheus
- exporter
- finops
home: https://github.com/COPRS/monitoring/blob/main/finops/object_storage_exporter/helm
sources:
- https://github.com/COPRS/monitoring/blob/main/finops/object_storage_exporter
maintainers:
- name: CS Group
