{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}
  labels:
{{ include "prometheus-exporter.labels" . | indent 4 }}
{{- end -}}