spring:
  application:
    name: trace-filter
  profiles:
    default: dev
  main:
    banner-mode: off
  cloud:
    stream:
      function:
        definition: trace-filter
        bindings:
          trace-filter-in-0: input
          trace-filter-out-0: output

logging:
  level:
    eu:
      csgroup:
        coprs: TRACE

info:
  app:
    description: ^project.description^
    name: ^project.artifactId^
    version: ^project.version^

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    eu:
      csgroup:
        coprs: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true