version: "3.7"

services:

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trace
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=postgresql
      - REPMGR_NODE_NETWORK_NAME=postgresql
      - REPMGR_NODE_NAME=postgresql-0
      - REPMGR_PARTNER_NODES=postgresql
    # networks:
    #   s1pdgs:
    #     ipv4_address: 172.16.238.60

 

  grafana:
    image: grafana/grafana:9.0.2
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/plugins/cs-invalidations:/var/lib/grafana/plugins/cs-invalidations
      - ./grafana/plugins/queue-error-management:/var/lib/grafana/plugins/queue-error-management
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/dashboards

    ports:
      - '3000:3000'
    # networks:
    #   s1pdgs:
    #     ipv4_address: 172.16.238.130

  

# networks:
#   s1pdgs:
#     ipam:
#       driver: default
#       config:
#         - subnet: "172.16.238.0/24"


