[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.29.26"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
