apiVersion: v1

kind: Secret

type: Opaque

data:
  spring.datasource.password: "{{ postgres.password }}"
  spring.datasource.username: "{{ postgres.username }}"
  spring.datasource.url: "jdbc:postgresql://{{ postgres.url }}:5432/trace"

metadata:
  name: trace-ingestor
  namespace: monitoring
