[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.1.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "0.17.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"

[prune]
  go-tests = true
  unused-packages = true