name: RS CORE Monitoring

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    paths:
      - 'rs-core/**'
      - '.github/workflows/rs-core.yml'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  REGISTRY_BASE: artifactory.coprs.esa-copernicus.eu
  RS_CORE_NAME: RS_CORE_MONITORING
  ARTIFACTORY_PROJECT: rs-zip
  ARTIFACTORY_USERNAME: ${{ secrets.CS_ARTIFACTORY_USER }}
  ARTIFACTORY_PASSWORD: ${{ secrets.CS_ARTIFACTORY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     component: [object-storage-exporter, resources-exporter]
    # permissions:
    #   contents: read
    #   packages: write
    #   security-events: write

    steps:

      - name: Set environment variables
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          GIT_TAG=${GITHUB_REF/refs\/tags\//}
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
  
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
          
      - name: Rename directory of RS-CORE
        run: mv rs-core ${{ env.RS_CORE_NAME }}_${{ env.GIT_TAG }}_Executables
        
      - name: Zip RS-CORE
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ env.RS_CORE_NAME }}_${{ env.GIT_TAG }}.zip ${{ env.RS_CORE_NAME }}_${{ env.GIT_TAG }}_Executables

      - name: Push to Artifactory
        run: curl -u "${{ env.ARTIFACTORY_USERNAME }}:${{ env.ARTIFACTORY_PASSWORD }}" -T ${{ env.RS_CORE_NAME }}_${{ env.GIT_TAG }}.zip "https://artifactory.coprs.esa-copernicus.eu/artifactory/${{ env.ARTIFACTORY_PROJECT }}/${{ env.RS_CORE_NAME }}_${{ env.GIT_TAG }}.zip"

